name: my first workflow
on:
  push:

jobs:
  my_first_pipeline:
    runs-on: ubuntu-latest
    
    steps:

    - name: cow saysomething
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: ${{github.ref_name}}
        color: 'red'
        
        - name: checkout repo
          uses: actions/checkout@v3

        - name: list the files in our repo
          run: ls -l
