name: my first workflow
on:
  push:

jobs:
  my_first_pipeline:
    runs-on: ubuntu-latest
    
    steps:
    - name: echo test
      run: echo "hello world"

    - name: what is the time on the runner
      run: date

    - name: list filesystem
      run: ls -l /

    - name: cow saysomething
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'hello dipsa56'
        color: 'blue'
